PREFIX sh:<http://www.w3.org/ns/shacl#> 
PREFIX sd:<http://www.w3.org/ns/sparql-service-description#> 
PREFIX void:<http://rdfs.org/ns/void#> 
PREFIX void_ext:<http://ldf.fi/void-ext#> 

SELECT DISTINCT
?classFrom
?datatypeTo
?classTo
?propIri
(SUM(?triples) AS ?sumTriples)
WHERE {
  ?graphIri sd:graph ?graph .
  ?s sd:graph ?graph .
  ?graph void:classPartition ?cp1 .
  ?cp1 void:class ?classFrom .
  ?cp1 void:propertyPartition ?pp1 .
  ?pp1 void:property ?propIri .
  ?pp1 void:triples ?triples .
  {
    ?pp1 void_ext:datatypePartition ?cp2 .
    ?cp2 void_ext:datatype ?datatypeTo .
  } UNION {
    ?pp1 void:classPartition ?cp2 .
    ?cp2 void:class ?classTo .
    ?graph void:classPartition ?cp3 .
    ?cp3 void:class ?classTo .  
  }
} GROUP BY ?classFrom ?classTo ?datatypeTo ?propIri ORDER BY ?classFrom ?classTo ?datatypeTo ?propIri